# Generated by Django 4.1.4 on 2023-05-31 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_number', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('protien', models.DecimalField(decimal_places=2, max_digits=5, max_length=1, null=True)),
                ('weight', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill_app.customer')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
