# Generated by Django 5.1 on 2024-09-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='cus_id',
            new_name='customer',
        ),
    ]
