# Generated by Django 5.1 on 2024-09-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='cus_note',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cus_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
