# Generated by Django 5.1 on 2024-09-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_rename_cus_id_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
