# Generated by Django 5.1 on 2024-09-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_customer_cus_acc_customer_cus_note_customer_cus_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cus_paid',
        ),
        migrations.CreateModel(
            name='Bills_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('cus_paid', models.IntegerField(default=0)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.product')),
            ],
        ),
    ]
