# Generated by Django 5.1 on 2024-09-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_remove_bill_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
